### ISSUE TITLE
Update Fig4.png

### ISSUE THREAD

**Issue by Enro** [aschetti/INOSC-starter-kit#12]
It seems that Brian Nosek has an updated version of image [content/en/docs/chapter1/fig4.png](https://github.com/aschetti/INOSC-starter-kit/blob/1a240998968169e6b6c0aacd5483ac6c6c845b60/content/en/docs/chapter1/fig4.png), [looking at his talk](https://youtu.be/xueB9tij9s0?t=2206). Is it possible to update the Starter Kit as well?

**Comment by aschetti** [comment]
I am not sure whether Wageningen has officially launched their OSC... I will ask Anita (the creator of this image) and let you know.

**Comment by aschetti** [comment]
Happy New Year @Enro ! 

I updated Figure 4 (in both the English and French versions of the starter kit) and also changed the orientation: the horizontal spread made it difficult to read the names of the OSCs. Let me know if you like it or you want to revert back to the original.

Could you please update the French description of Figure 4 in the text of Chapter 1? Also, do you want to open a new issue for that or shall we keep this issue open until the description is updated?

**Comment by Enro** [comment]
Thank you very much @aschetti and Happy New Year to you!

I have updated the French text for Figure 4, the pull request is here: https://github.com/aschetti/INOSC-starter-kit/pull/14
